[Include]
Include=../base/mkosi.conf

[Output]
Output=puffin-server-x86-64
ImageId=puffin-server
RepartDirectories=../base/mkosi.repart

[Content]
ExtraTrees=
        ../base/mkosi.extra
        ../shared/mkosi.extra
PostInstallationScripts=../shared/mkosi.postinst.chroot
FinalizeScripts=../base/mkosi.finalize
Packages=
        bind
        cloud-init
        dmidecode
        docker
        ethtool
        firewalld
        htop
        iotop-c
        jq
        less
        lsof
        mise
        nano
        nvme-cli
        openssh
        podman
        rsync
        runc
        smartmontools
        strace
        sudo
        tcpdump
        tmux
        tree
        vim
