#!/bin/sh
set -eu

test "$(findmnt -n -o FSTYPE /)" = erofs
findmnt -n -o OPTIONS / | grep -qw ro
root_source=$(findmnt -n -o SOURCE /)
case "$root_source" in /dev/mapper/*) ;; *) exit 1 ;; esac
dmsetup table "${root_source#/dev/mapper/}" | grep -q ' verity '

test "$(findmnt -n -o FSTYPE /etc)" = overlay
findmnt -n -o OPTIONS /etc | grep -qw rw
test "$(findmnt -n -S LABEL=puffin_etc -o TARGET)" = /run/puffin-etc

findmnt -n -o OPTIONS /var | grep -qw rw
