[Include]
Include=../../base/mkosi.conf

[Output]
Output=puffin-desktop-installer-x86-64
OutputDirectory=../../out
ImageId=puffin-desktop-installer
RepartDirectories=mkosi.repart

[Content]
ExtraTrees=
        ../../base/mkosi.extra
        ../../out/desktop-installer-tree
Initrds=
Initrds=../../out/initrd
Packages=
        cage
        cryptsetup
        dconf
        gtk4
        kbd
        libadwaita
        mesa
        openssl
        python
        python-gobject
        seatd
        xorg-xwayland
        zstd

[Build]
CacheDirectory=../../.cache/mkosi
PackageCacheDirectory=../../.cache/packages
