[Config]
MinimumVersion=26
Dependencies=initrd

[Distribution]
Distribution=arch
Architecture=x86-64
Snapshot=2026/07/29
RepositoryKeyCheck=yes
RepositoryKeyFetch=yes

[Output]
Format=disk
Output=puffin-base-x86-64
OutputDirectory=../out
CompressOutput=no
ManifestFormat=json
ImageId=puffin-base
ImageVersion=0.1.0

[Build]
CacheDirectory=../.cache/mkosi
PackageCacheDirectory=../.cache/packages

[Content]
Packages=
        base
        linux
        linux-firmware
        amd-ucode
        intel-ucode
        gnupg
Locale=en_US.UTF-8
MachineId=
CleanPackageMetadata=yes
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
MicrocodeHost=no
KernelCommandLine=console=tty0 console=ttyS0,115200n8 systemd.firstboot=no systemd.gpt_auto=0
Initrds=%O/initrd

[Validation]
SecureBoot=yes
