[Include]
Include=../base/mkosi.conf

[Output]
Output=puffin-desktop-x86-64
ImageId=puffin-desktop
RepartDirectories=../base/mkosi.repart

[Content]
ExtraTrees=
        ../base/mkosi.extra
        ../shared/mkosi.extra
PostInstallationScripts=../shared/mkosi.postinst.chroot
FinalizeScripts=../base/mkosi.finalize
KernelCommandLine=
KernelCommandLine=console=tty0 console=ttyS0,115200n8 systemd.firstboot=no systemd.gpt_auto=0 quiet splash plymouth.ignore-serial-consoles
Packages=
        accountsservice
        bluez
        bluez-utils
        bolt
        cups
        cups-pk-helper
        dconf
        firewalld
        flatpak
        fprintd
        fwupd
        gdm
        glibc-locales
        gnome-backgrounds
        gnome-console
        gnome-control-center
        gnome-disk-utility
        gnome-keyring
        gnome-menus
        gnome-session
        gnome-settings-daemon
        gnome-shell
        gnome-system-monitor
        gnome-tour
        gnome-user-docs
        gst-plugin-pipewire
        gvfs
        gvfs-afc
        gvfs-goa
        gvfs-gphoto2
        gvfs-mtp
        gvfs-nfs
        gvfs-smb
        iio-sensor-proxy
        intel-media-driver
        libva-mesa-driver
        malcontent
        mesa
        mise
        modemmanager
        nautilus
        networkmanager
        noto-fonts
        noto-fonts-cjk
        noto-fonts-emoji
        orca
        pipewire
        pipewire-alsa
        pipewire-audio
        pipewire-jack
        pipewire-pulse
        plymouth
        power-profiles-daemon
        sof-firmware
        sudo
        switcheroo-control
        tecla
        vulkan-intel
        vulkan-nouveau
        vulkan-radeon
        wireplumber
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk
        yelp
RemoveFiles=
        /usr/share/applications/avahi-discover.desktop
        /usr/share/applications/bssh.desktop
        /usr/share/applications/bvnc.desktop
        /usr/share/applications/cups.desktop
        /usr/share/applications/lstopo.desktop
        /usr/share/applications/qv4l2.desktop
        /usr/share/applications/qvidcap.desktop
